// Generated by CoffeeScript 1.10.0
(function() {
  var ready, rotate1Times, rotate2Times, rotateAnim, rotationDegrees, test;

  rotationDegrees = [0, 0, 0, 0];

  test = 0;

  rotate1Times = [];

  rotate2Times = [];

  ready = function() {
    var degree, doc, loading, mouse, mousee, output, screenCenter;
    output = $("#output");
    loading = $("#loading");
    degree = $("#debug_degree");
    mousee = $("#mousee");
    screenCenter = {
      x: $(document).width() / 2,
      y: $(document).height() / 2
    };
    output.css({
      'bottom': "90px"
    });
    output.css({
      'left': screenCenter.x - output.width() / 2
    });
    doc = $(document);
    mouse = {
      x: 1,
      y: 1
    };
    $(window).mousemove(function(event) {
      mouse.x = event.pageX;
      return mouse.y = event.pageY;
    });
    setInterval((function() {
      var rotate1Time, start;
      start = performance.now();
      rotateAnim(90, 0.15, "#output", "#output2");
      rotateAnim(90, 0.1, "#output2", "#output3");
      rotateAnim(90, 0.05, "#output3", "#output4");
      rotateAnim(90, 0.0, "#output4", "#none");
      output.css({
        "left": screenCenter.x - mouse.x / 4
      });
      rotate1Time = performance.now() - start;
      return rotate1Times.push(rotate1Time);
    }), 1);
    return setInterval((function() {
      var avg, i, j, len, len1, sum, time;
      sum = 0;
      for (i = 0, len = rotate1Times.length; i < len; i++) {
        time = rotate1Times[i];
        sum += time;
      }
      avg = sum / rotate1Times.length;
      rotate1Times = [];
      $('#ms1').text('Rotate 1 takes about ' + avg + 'ms to execute and runs for ' + sum + 'ms every second.');
      sum = 0;
      for (j = 0, len1 = rotate2Times.length; j < len1; j++) {
        time = rotate2Times[j];
        sum += time;
      }
      avg = sum / rotate2Times.length;
      rotate2Times = [];
      return $('#ms2').text('Rotate 2 takes about ' + avg + 'ms to execute and runs for ' + sum + 'ms every second.');
    }), 1000);
  };

  rotateAnim = function(degree, speed, target, bouncer) {
    var $bouncer, $target, degree_var, matrix, rads;
    degree_var = 0;
    $target = $(target);
    $bouncer = $(bouncer);
    $(target).css({
      '-webkit-transform': 'rotate(' + degree_var + 'deg)',
      '-moz-transform': 'rotate(' + degree_var + 'deg)',
      '-ms-transform': 'rotate(' + degree_var + 'deg)',
      '-o-transform': 'rotate(' + degree_var + 'deg)',
      'transform': 'rotate(' + degree_var + 'deg)'
    });
    rads = degree_var / (180 / Math.PI);
    matrix = ($target.height() * Math.sin(rads) + $target.height() * Math.cos(rads)) * -1;
    $bouncer.css({
      'top': matrix + $target.offset().top + $target.height() - $bouncer.height() - 15
    });
    $bouncer.css({
      'left': $target.css('left')
    });
    if (degree_var < degree) {
      degree_var += speed;
      console.log(degree_var);
    } else {
      degree_var = 0;
    }
    return degree_var;
  };

  $(document).ready(ready);

}).call(this);
